### ISSUE TITLE
Compute Mode

### ISSUE THREAD

**Issue by mike-giles** [jade-hpc-gpu/jade-hpc-gpu.github.io#1]
The current compute mode is default.

I think this should be changed to exclusive-process or possibly exclusive-process-and-thread:

http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#compute-modes

**Comment by LiamATOS** [comment]
This is now resolved

**Comment by martinjhnhadley** [comment]
Closed as agreed in call
