### ISSUE TITLE
Upgrade CUDA version (required OS upgrade too)

### ISSUE THREAD

**Issue by andygittings** [jade-hpc-gpu/jade-hpc-gpu.github.io#10]
I have just checked the NVidia driver version on a compute node and this is currently 375.66. This needs to be upgraded to 384.00 (or later) to support CUDA 9.0

Fri Oct 13 10:03:51 2017       
NVIDIA-SMI 375.66                 Driver Version: 375.66                    

If a CUDA 9.0 executable is run the following error is produced:
CUDA error at test.cu:44 code=35(cudaErrorInsufficientDriver) "cudaMalloc((void **)&d_u, sizeof(float)*NX)" 

CUDA 8.0 is fine.

**Comment by LiamATOS** [comment]
CUDA 9 requires a DGX Update and we are currently in the process of planning this cluster wide update

Thanks

LJ

**Comment by LiamATOS** [comment]
We are planning on rolling out the new DGX Image Update next week, please keep an eye on the MOTD on the login nodes for daily updates as this will be rolling upgrade. The cluster will still be available but the SLURM Partitions may change throughout the week.

Thanks

Liam

**Comment by martinjhnhadley** [comment]
Liam notified us on the call this has been done now.
