### ISSUE TITLE
Update Singularity

### ISSUE THREAD

**Issue by henzler** [jade-hpc-gpu/jade-hpc-gpu.github.io#100]
# Software Request

Would it be possible to update Singularity to the latest version? Currently, only version 2.4 is installed which leads to compatibility problems when creating images using newer versions.

**Comment by f90** [comment]
Version 3.3 is installed now apparently, so I think this can be closed?

**Comment by henzler** [comment]
I have not double-checked yet, but I guess you can close it, thank you!!
