### ISSUE TITLE
Software Request: Latest PGI compilers (v 19.5)

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#104]
# Software Request

We've had some request for updating the PGI compilers to be used in the upcoming hackathon in Sheffield. Is this possible?

**Comment by twinkarma** [comment]
Requested by @mozhgan-kch

**Comment by twinkarma** [comment]
@LiamATOS let me or @mozhgan-kch know if you need more information on this.

**Comment by LiamATOS** [comment]
Request to STFC made for SW Install,will chase tomorrow

**Comment by twinkarma** [comment]
@LiamATOS any updates on this?

**Comment by LiamATOS** [comment]
Twin,

It looks like 19.5 and later versions are now licensed. Do we have a license for this?

Thanks

Liam

**Comment by twinkarma** [comment]
Not for 19.5 but I've spoken to @mozhgan-kch and seems that the 19.4 community edition is ok so we should go ahead with that.

**Comment by jimboid** [comment]
@twinkarma I've installed PGI 19.4 on JADE. Do your devs have an account on there to test it out before the hackathon?

**Comment by twinkarma** [comment]
Thank you I'll chase it up with them

**Comment by twinkarma** [comment]
A further issue is reported, any clues on this?:

With 19.4 version,
I get the following errors.

CMake Error at /jmain01/apps/gcc/cmake/3.10.2/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:174 (file):
  file failed to open for writing (File too large):

    /jmain01/home/JAD044/txk15/cck88-txk15/projects/XCFD/build-pgi/CMakeFiles/CMakeOutput.log


But, the issue is somewhere else. I am not allowed to create any new files or save modified files. I logged out and logged in again. It didn't help.

**Comment by jimboid** [comment]
I had a similar problem yesterday when rsyncing files to the jade login nodes. @LiamATOS is there some disk or cache that is causing this?

**Comment by twinkarma** [comment]
v19.4 is now installed and the disk problem is unrelated to this issue.
