### ISSUE TITLE
Running a visualisation GUI application (ITK-SNAP) on JADE through xserver, is it possible?

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#106]
I have a group (@joshastley) who uses DL to generate 3D medical images. They would like to preview these generated results directly through a GUI application (ITK-SNAP) on the cluster and wondering if this is possible.

**Comment by LiamATOS** [comment]
Its possible...but probably only with some SSH Tunnelling as I would be hesitant to have this on the login nodes.

How about, I install on devel node for now and see how it goes?

Thanks

Liam

**Comment by LiamATOS** [comment]
Its possible...but probably only with some SSH Tunnelling as I would be hesitant to have this on the login nodes.

How about, I install on devel node for now and see how it goes?

Thanks

Liam

**Comment by LiamATOS** [comment]
Hi,

Users can just download the binary themselves and run.

I have installed the libglu depenandancy on the devel node and can run the basic binary.

ljj24-ljj01@dgj318:/jmain01/apps/itksnap/bin$ pwd
/jmain01/apps/itksnap/bin
ljj24-ljj01@dgj318:/jmain01/apps/itksnap/bin$ ls
itksnap
ljj24-ljj01@dgj318:/jmain01/apps/itksnap/bin$ ./itksnap -h
ITK-SnAP Command Line Usage:
   /jmain01/apps/itksnap/lib/snap-3.6.0/ITK-SNAP [options] [main_image]
Image Options:
   -g FILE              : Load the main image from FILE
   -s FILE              : Load the segmentation image from FILE
   -l FILE              : Load label descriptions from FILE
   -o FILE [FILE+]      : Load additional images from FILE
                        :   (multiple files may be provided)
   -w FILE              : Load workspace from FILE
                        :   (-w cannot be mixed with -g,-s,-l,-o options)
Additional Options:
   -z FACTOR            : Specify initial zoom in screen pixels/mm
   --cwd PATH           : Start with PATH as the initial directory
   --threads N          : Limit maximum number of CPU cores used to N.
   --scale N            : Scale all GUI elements by factor of N (e.g., 2).
Debugging/Testing Options:
   --debug-events       : Dump information regarding UI events
   --test list          : List available tests.
   --test TESTID        : Execute a test.
   --testdir DIR        : Set the root directory for tests.
   --testacc factor     : Adjust the interval between test commands by factor (e.g., 0.5).
   --css file           : Read stylesheet from file.
   --opengl MAJOR MINOR : Set the OpenGL major and minor version. Experimental.
   --testgl             : Diagnose OpenGL/VTK issues.
Platform-Specific Options:
ljj24-ljj01@dgj318:/jmain01/apps/itksnap/bin$

**Comment by twinkarma** [comment]
Closed due to inactivity
