### ISSUE TITLE
Singularity module not available

### ISSUE THREAD

**Issue by f90** [jade-hpc-gpu/jade-hpc-gpu.github.io#108]
``module load singularity`` stopped working on the JADE servers, on the login node as well as when running a run-script on the development nodes. ``module avail`` also doesn't show singularity anymore.

Yesterday it still worked. I need to use singularity to run my research on JADE as it does not provide sound processing libraries such as libsndfile that I need in my project.

**Comment by f90** [comment]
Today I tried again and it now all i see in ``module avail`` is a new entry ``singularity/3.3.0``, seems like the version was updated? Unfortunately when I load it, the ``singularity`` command is not found, so something is wrong there with the installation. Also there are only binaries for 2.3.1 and 2.4 in the ``/jmain01/apps/singularity/`` path, so maybe an incomplete installation?

**Comment by LiamATOS** [comment]
Hi All,

Apologies for the delay, I am having some email issues.

STFC spotted we were using an old version and it had a critical security vulnerability we needed to patch with an update.

I have asked them to check the module though as not sure why no binaries were showing as they said the install was complete.

Thanks

Kind regards,

[Atos logo]     Liam Jones
HPC Engineer – Big Data & Security UK&I
M: +44 (0) 7583 010542
atos.net<https://atos.net/>



________________________________

**Comment by f90** [comment]
Issue appears to be fixed. I can confirm the update, singularity is on 3.3 now. Thank you!
