### ISSUE TITLE
No e-mails received for job status even when specified in batch script

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#12]
Even when specifying email alert in the batch script file, no e-mail is sent about job status e.g.:

```
#SBATCH --mail-type=ALL
#SBATCH --mail-user=my.mail@institution.ac.uk
```

**Comment by martinjhnhadley** [comment]
@twinkarma does this remain an issue?

**Comment by abewley** [comment]
Yes, I too am experiencing this issue.

**Comment by LiamATOS** [comment]
STFC need to enable email relay from xCAT - Request raised for this 17/10

**Comment by martinjhnhadley** [comment]
Liam is still awaiting an update

**Comment by twinkarma** [comment]
I seem to be getting e-mails now so I guess it's been implemented?

**Comment by LiamATOS** [comment]
that's great, this can now be closed

**Comment by martinengelcke** [comment]
I am not receiving any emails regarding my jobs. Did something change?

**Comment by ziqizhang** [comment]
I also have problems receiving emails. Jobs are submitted, and finished. But no emails received.
