### ISSUE TITLE
CUDA_VISIBLE_DEVICES environment variable not passed in to Docker containers

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#13]
This visible devices lock used to limit which GPU a user is able to utilise and is essential when there's multiple users sharing a single node.

When NOT using containers the environment variables are set:

```
srun --partition=big --gres=gpu:2 printenv | grep CUDA_VISIBLE_DEVICES

CUDA_VISIBLE_DEVICES=2,3

```
but when using a docker container e.g. Caffe, the same command does not show the environment variable:

```
srun --gres=gpu:2 --pty  /jmain01/apps/docker/caffe 17.04

printenv | grep CUDA_VISIBLE_DEVICES
#Noting is shown
```
I've also tested using the `deviceQuery` from the CUDA sample code and it shows that 8 devices are detected instead of just the 2 that was requested.

**Comment by Parker-A** [comment]
Hi
This has been resolved. There was a bug in the interactive script.
You should only be able to see the GPUs you have been allocated by Slurm.
If you try it now, if you ask for 2 GPUS, you will only see 2 GPUs inside the container.
Adam

**Comment by martinjhnhadley** [comment]
Closed as appears to be resolved. @twinkarma please do re-open if needs be
