### ISSUE TITLE
lots of lustre client error messages in dmesg

### ISSUE THREAD

**Issue by sbutcher** [jade-hpc-gpu/jade-hpc-gpu.github.io#14]
[Mon Oct 16 09:50:06 2017] Lustre: 2449:0:(client.c:2141:ptlrpc_expire_one_request()) Skipped 24 previous similar messages
[Mon Oct 16 09:54:43 2017] LNet: 2431:0:(o2iblnd_cb.c:3174:kiblnd_check_conns()) Timed out tx for 172.31.126.87@o2ib: 403055 seconds
[Mon Oct 16 09:54:43 2017] LNet: 2431:0:(o2iblnd_cb.c:3174:kiblnd_check_conns()) Skipped 24 previous similar messages
[Mon Oct 16 10:00:12 2017] Lustre: 2449:0:(client.c:2141:ptlrpc_expire_one_request()) @@@ Request sent has failed due to network error: [sent 1508144508/real 1508144518]  req@ffff880eb14da700 x1570198182041824/t0(0) o250->MGC172.31.126.87@o2ib@172.31.126.87@o2ib:26/25 lens 520/544 e 0 to 1 dl 1508144563 ref 1 fl Rpc:eXN/0/ffffffff rc 0/-1
[Mon Oct 16 10:00:12 2017] Lustre: 2449:0:(client.c:2141:ptlrpc_expire_one_request()) Skipped 23 previous similar messages
[Mon Oct 16 10:04:49 2017] LNet: 2431:0:(o2iblnd_cb.c:3174:kiblnd_check_conns()) Timed out tx for 172.31.126.87@o2ib: 403661 seconds
[Mon Oct 16 10:04:49 2017] LNet: 2431:0:(o2iblnd_cb.c:3174:kiblnd_check_conns()) Skipped 23 previous similar messages
[Mon Oct 16 10:06:17 2017] LustreError: 11-0: jmain01-MDT0000-mdc-ffff88203810d800: operation obd_ping to node 172.31.126.88@o2ib failed: rc = -107
[Mon Oct 16 10:06:17 2017] Lustre: jmain01-MDT0000-mdc-ffff88203810d800: Connection to jmain01-MDT0000 (at 172.31.126.88@o2ib) was lost; in progress operations using this service will wait for recovery to complete
[Mon Oct 16 10:06:42 2017] Lustre: Evicted from MGS (at 172.31.126.87@o2ib) after server handle changed from 0xd6ababdf85da5a9c to 0x4b07f84b4896d6ea
[Mon Oct 16 10:06:42 2017] Lustre: MGC172.31.126.87@o2ib: Connection restored to 172.31.126.87@o2ib (at 172.31.126.87@o2ib)
[Mon Oct 16 10:07:15 2017] Lustre: jmain01-MDT0000-mdc-ffff88203810d800: Connection restored to 172.31.126.87@o2ib (at 172.31.126.87@o2ib)

**Comment by Parker-A** [comment]
We had an issue with one of the OSS's, this has now been resolved.
Adam

**Comment by martinjhnhadley** [comment]
Closing as Adam feeds back this has been resolved.
