### ISSUE TITLE
sacct no working

### ISSUE THREAD

**Issue by mourga** [jade-hpc-gpu/jade-hpc-gpu.github.io#140]
Hi, I was using ``sacct`` to track my submitted/pending/ended jobs but now it's not working anymore for some reason. I get ``sacct: error: slurmdbd: Operation not permitted``.

Do you know why is this happening?

Thank you in advance.

**Comment by twinkarma** [comment]
@LiamATOS Any ideas why this is happening?

**Comment by LiamATOS** [comment]
Hi,

Please try again and if the issue persistes, send me the full command and location of where you are running as I can't see anything wrong when running sacct queries.

Thanjs

Liam
T

**Comment by mourga** [comment]
@twinkarma @LiamATOS Thanks it is working again now!
