### ISSUE TITLE
website: old link on /access

### ISSUE THREAD

**Issue by twak** [jade-hpc-gpu/jade-hpc-gpu.github.io#142]
webpage: https://www.jade.ac.uk/access/
issue: "Other Applications of JADE" subsection links to EPSRC RAPs which closed in 2017.

use-case: I'm looking for information about how to apply for time on Jade as a member of a UK, but non-partner-university.

Cheers, tom

**Comment by twinkarma** [comment]
Hi Tom, JADE will soon be coming to the end of its life and will be superseded with JADE 2 later this year. There'll be an access policy for the new system soon but unfortunately I don't have the date for it yet.

**Comment by twak** [comment]
Thanks! So there won't be a Autumn RAP call?

**Comment by twak** [comment]
Ah, just found the [Turing call for Jade compute](https://www.turing.ac.uk/work-turing/turing-call-jade-applications-june-2020) (deadline is the end of June)
