### ISSUE TITLE
Can't connect to internet to download software while in docker container but builds on head nodes has library conflicts

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#16]
While in a docker container because you're running on the compute note it is not possible to connect to the internet and download python modules or use package managers. 

When building software outside of the container (e.g. on the head node), as the linked libraries are different, users have experienced library conflicts.

**Comment by martinjhnhadley** [comment]
@twinkarma is this still an issue?

**Comment by martinjhnhadley** [comment]
Noted at 2017/11/10 that these issues are linked https://github.com/jade-hpc-gpu/jade-hpc-gpu.github.io/issues/15

It would be easier with singularity as well (see https://github.com/jade-hpc-gpu/jade-hpc-gpu.github.io/issues/18)

**Comment by twinkarma** [comment]
Singularity and Anaconda installed so users can opt to create their custom image/virtual environment using those.
