### ISSUE TITLE
Default conda module breaking basic functionalities. 

### ISSUE THREAD

**Issue by WillGPoole** [jade-hpc-gpu/jade-hpc-gpu.github.io#172]
Hi,

Using the default anaconda module on JADE seems to break basic Linux functions such as ls and vi. Messes with some important library by the looks of it. 

```
module load python/anaconda3
ls
ls: relocation error: /lib64/libacl.so.1: symbol getxattr, version ATTR_1.0 not defined in file libattr.so.1 with link time reference
vi
vim: relocation error: /lib64/libacl.so.1: symbol getxattr, version ATTR_1.0 not defined in file libattr.so.1 with link time reference
```

Thanks,

Will

**Comment by andygittings** [comment]
This was reported in ServiceNow ticket CS0003540

It now appears to be fixed as the "ls" command works after loading anaconda3
