### ISSUE TITLE
Difference between partition long and big.

### ISSUE THREAD

**Issue by franciszzj** [jade-hpc-gpu/jade-hpc-gpu.github.io#178]
Hi, I found nodes in partition long and big are same.
So I want to know is there any difference between long and big?
For example, when I submit a job to Jade, whether there is a difference in the priority for two partitions.

**Comment by twinkarma** [comment]
As far as I know there shouldn't be a difference in priority, only that you can submit jobs that run longer. However, the longer the job, the harder it is for the scheduler to find a slot for it, normally resulting in a longer waiting time before it can run.
