### ISSUE TITLE
Use of custom Docker containers

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#18]
In ML applications it is the norm to use a combination of different python packages beside the main ML package. As internet cannot be used on the compute node, new packages cannot be downloaded in to the containers.

Being able to use custom docker containers would greatly help with the research workflow.

**Comment by Parker-A** [comment]
Hi
Custom docker containers are not allowed as the container itself runs as root. We will investigate the usage of Singularity, then users could use their own Singularity containers.
There are tools to convert docker containers into Singularity.
Adam

**Comment by twinkarma** [comment]
Singularity is installed and and working as an alternative so we can close this issue.
