### ISSUE TITLE
Installation of Anaconda as modules

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#19]
[Anaconda](https://www.anaconda.com) supports virtual local environment that allows users to easily install  custom stack of c/c++ and python packages to their own home directory. At Sheffield we have modules of Anaconda for both Python 2 and 3, we probably still need to support Python 2 for a while as the code is still quite prolific (at least in ML applications).

We have documented the software on our Sheffield cluster here if it's any help:
http://docs.hpc.shef.ac.uk/en/latest/iceberg/software/apps/python.html?highlight=python

**Comment by LiamATOS** [comment]
Hi,

This is now complete, we have anaconda modules for both Python 2 and 3.

Thanks

LJ

**Comment by martinjhnhadley** [comment]
Closed until @twinkarma has any updates
