### ISSUE TITLE
Software request: readline, readline-devel

### ISSUE THREAD

**Issue by schroeder-dewitt** [jade-hpc-gpu/jade-hpc-gpu.github.io#20]
I am trying to compile Torch7 in my home dir (as suggested by support - Mihai Duta). Compilation fails because packages readline, readline-devel are missing.

Can you please install these asap + check if torch requires any other packages to compile?

Thanks and regards

Christian Schroeder

**Comment by Parker-A** [comment]
Hi
There is a Torch Docker image, provided by NVidia. Have you tried using that ?
Adam

**Comment by martinjhnhadley** [comment]
@schroeder-dewitt did this suggestion from Adam help?

**Comment by twinkarma** [comment]
Also here's the documentation for Torch on JADE:
http://docs.jade.ac.uk/en/latest/software/machine-learning/torch.html

**Comment by LiamATOS** [comment]
I think this is now resolved..Christian, can you confirm please?

**Comment by martinjhnhadley** [comment]
@schroeder-dewitt Hello Christian, is this still an issue for you? We would like to get this fixed for you.

**Comment by martinjhnhadley** [comment]
Closed as no follow up
