### ISSUE TITLE
Full list of compilers on JADE

### ISSUE THREAD

**Issue by martinjhnhadley** [jade-hpc-gpu/jade-hpc-gpu.github.io#21]
Need this list

**Comment by LiamATOS** [comment]
This is a dump from the Login Node of the modules environement

ljj24-sja01@dgj419:~$ module avail

------------------------------------------------------------------------------------------ /jmain01/apps/modules -------------------------------------------------------------------------------------------
cuda/8.0                 gcc/5.5.0                IntelMKL/2017.3.196      openmpi/1.10.5a1/GNU     pgi/2017                 PrgEnv-pgi/17.4(default) python3/3.6.3(default)   utilities
emacs/25.3               gromacs/2016.3           NAMD/2.12                openmpi/2.1.2            pgi64/17.4(default)      python2/2.7.14(default)  python3/anaconda
ffmpeg/3.4               gromacs/5.1.2            openmpi/1.10.2/2017      pgi/17.4(default)        pgi64/2017               python2/anaconda         test-mod/2.26.1

--------------------------------------------------------------------------------------- /usr/share/modules/versions ----------------------------------------------------------------------------------------
3.2.10

-------------------------------------------------------------------------------------- /usr/share/modules/modulefiles --------------------------------------------------------------------------------------
dot         module-git  module-info modules     null        use.own

**Comment by LiamATOS** [comment]
There was no Intel License so I think the Intel Module was on a temp license for the HPL Run

**Comment by martinjhnhadley** [comment]
This is now available on the website
