### ISSUE TITLE
Test CUDA 9 with ML software on JADE

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#25]
Check that supported ML software on JADE are working with CUDA 9:

* Anaconda
  * [x] Tensorflow
  * [x] Theano
  * [ ] PyTorch
* Docker
  * [x] Caffe
  * [x] Tensorflow
  * [x] Theano
  * [x] Torch
* Singularity
  * [x] Caffe
  * [x] Tensorflow
  * [x] Theano
  * [ ] PyTorch

**Comment by twinkarma** [comment]
@Parker-A

I'm currently testing the expr node

Can I check that I only have to add --partition=expr to my srun or sbatch scripts (#SBATCH --partition=expr) to get on to the experimental node is that right? 

When I run it i'm getting node `dgj104`

Will you also create a cuda 9.0 module? As when I do a `module avail` I don't see it:

```
txk31-txk03@dgj104:~$ module avail

--------------------------------------------------- /jmain01/apps/modules ----------------------------------------------------
cuda/8.0                 gromacs/5.1.2            openmpi/2.1.2            PrgEnv-pgi/17.4(default) singularity/2.4
emacs/25.3               IntelMKL/2017.3.196      pgi/17.4(default)        python2/2.7.14(default)  test-mod/2.26.1
ffmpeg/3.4               NAMD/2.12                pgi/2017                 python2/anaconda         utilities
gcc/5.5.0                openmpi/1.10.2/2017      pgi64/17.4(default)      python3/3.6.3(default)
gromacs/2016.3           openmpi/1.10.5a1/GNU     pgi64/2017               python3/anaconda

------------------------------------------------ /usr/share/modules/versions -------------------------------------------------
3.2.10

----------------------------------------------- /usr/share/modules/modulefiles -----------------------------------------------
dot         module-git  module-info modules     null        use.own

```

**Comment by Parker-A** [comment]
Hi
Yes that is right - just add "--partition=expr". Only node dgj104 is in that partition.
I've created a cuda 9 module. Making the cuda 8.0 module the default.

**Comment by twinkarma** [comment]
@Parker-A 

When I try to use `singinteractive` on the expr partition I get the follow error:

```
txk31-txk03@dgj223:~$ srun -I --pty -t 0-10:00 --gres gpu:1 -p expr singinteractive dl-python-gpu.simg
srun: error: Unable to allocate resources: Requested partition configuration not available now
```
And when I get an interactive session normally (still on the expr) and run something like

```
singularity shell dl-python-gpu.simg
```

When I go in to `/usr/local/cuda/lib64` I still see CUDA 9 bound on to the image which doesn't happen on other nodes. Looks like it's still using the old config file?

**Comment by Parker-A** [comment]
Hmm, give it a go now and I’ll watch it.

I noticed earlier today that hyperthreading was enabled on this node – so I disabled it & restarted slurmd. I thought it was OK.

I’ve just tested it and it seemed ok:

atostest@dgj223:~$ srun -I --pty -t 0:10 --gres gpu:1 -p expr /jmain01/apps/singularity/2.4/bin/singinteractive /jmain01/apps/singularity/singularity-images/caffe-gpu.img
CUDA_VISIBLE_DEVICES: 0
WARNING: Library bind directory not present in container, update container
Singularity: Invoking an interactive shell within container...

atostest@dgj104:~$ hostname
dgj104
atostest@dgj104:~$ exit

Are you doing something different to me ?

The singularity files are on the shared filesystem. SO all nodes see the same.
I created a link on the expr no from /usr/local/cuda to /usr/local/cuda-9.0

As part of the singularity config we map/bind:

bind path = /etc/localtime
bind path = /etc/hosts
bind path = /usr/local/cuda:/usr/local/cuda

On the "older" nodes we just map /usr/local/cuda to /usr/local/cuda-8.0

**Comment by twinkarma** [comment]
Ok it's working for my own image now as well. Looks like I need to give a full path to the singularity image for it to work. Whereas I just had dl-python-gpu.simg before I need to put /jmain01/home/JAD009/txk03/txk31-txk03/dl-python-gpu.img.

About the bind path, I see now, there's no problem running images on the other nodes because the ones I'm using are all built on CUDA 8. But when I run it on the expr node, the binding to CUDA 9 causes it to fail. We definitely should remove the cuda binding from the config.

**Comment by Parker-A** [comment]
Hi

OK, I've removed the binding to the /usr/local/cuda. Can you give it another go ?
Thanks

**Comment by twinkarma** [comment]
Ok, looks like the path has been unbound but I'm getting a different error instead which I don't get when I tested on the other nodes running the same image and example:

```
Singularity dl-python-gpu.simg:~/dgx_benchmarking/tf> python mnist_deep.py
Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
2018-01-12 15:57:33.384219: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-01-12 15:57:33.959519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: Tesla P100-SXM2-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.4805
pciBusID: 0000:06:00.0
totalMemory: 15.89GiB freeMemory: 15.60GiB
2018-01-12 15:57:33.959595: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0000:06:00.0, compute capability: 6.0)
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/util/tf_should_use.py:107: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
2018-01-12 15:57:35.421269: E tensorflow/stream_executor/cuda/cuda_blas.cc:366] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2018-01-12 15:57:35.437725: E tensorflow/stream_executor/cuda/cuda_blas.cc:366] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2018-01-12 15:57:35.503077: E tensorflow/stream_executor/cuda/cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2018-01-12 15:57:35.503101: E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
2018-01-12 15:57:35.503127: F tensorflow/core/kernels/conv_ops.cc:667] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)
Aborted

```

Strange as the CUDA versions should work independently of each other and the GPU drivers should be able to run older version of CUDA. I'll investigate next week.

**Comment by Parker-A** [comment]
Hi
Can I reboot the Ubuntu 16 node ? Need to test a new kernel.
Thanks

**Comment by twinkarma** [comment]
I'm not running anything on it at the moment so reboot away.

**Comment by Parker-A** [comment]
Thanks.
I've installed a new kernel with the Meltdown kernel fix in place & the new NVidia Drivers. I'd be interested to see if you see any performance issues. From what I have seen, unless your code is IO intensive, you should not really see anything.

**Comment by twinkarma** [comment]
@Parker-A I think we need to install cuDNN as well. It is now pretty much essential to have it in order to run DL software that uses GPU acceleration e.g. when trying to use Tensorflow through the Anaconda environment route.

I'd recommend cuDNN 6 for CUDA 8 (most widely supported currently) and cuDNN 7 for CUDA 9 to start off.

**Comment by Parker-A** [comment]
I'll look into cuDDN. 
How are you getting on otherwise ? We have a growing need to move towards cuda 9 from other users. All the latest NVidia docker containers now need cuda 9.
Thanks

**Comment by twinkarma** [comment]
I've tested all the docker images and they work fine. Need cuDNN on the nodes to be able to test Anaconda. 

I'm a bit stumped about Singularity and can't seem to get it to work but I think we can take a bit more time on it since the other two methods should work.

**Comment by twinkarma** [comment]
I can work on getting Singularity to work after the kernel updates and CUDA 9 rolled out is what I mean.

**Comment by twinkarma** [comment]
I've also tested Tensorflow 17.12 as well separately and it works but thought I'd check just to make sure.

**Comment by Parker-A** [comment]
I would recommend you test it with the latest versions. So use "-v VERSION" as well (Where VERSION is the TAG field below):

REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
nvcr.io/nvidia/pytorch      17.12               5ac6ff8f9a81        2 months ago        4.52GB
nvcr.io/nvidia/tensorflow   17.12               19afd620fc8e        2 months ago        2.88GB
nvcr.io/nvidia/caffe        17.11               74f90888fb24        2 months ago        3.25GB
nvcr.io/nvidia/theano       17.11               39aed30f94ed        2 months ago        3.37GB
nvcr.io/nvidia/torch        17.11               1fb9e886f48c        2 months ago        3.27GB
nvcr.io/nvidia/caffe2       17.10               2ff2ccd2c8c1        3 months ago        2.73GB

If you don't specify a version, it picks the original (oldest!).

**Comment by twinkarma** [comment]
Ah ok. I've gone through it again using the new versions and Tensorflow, Caffe, Theano and Torch works fine. I don't have test script for Pytorch and caffe2 handy but I don't foresee any problems if all the others have been fine.
