### ISSUE TITLE
Software Request: GROMACS 2018

### ISSUE THREAD

**Issue by ab24g12** [jade-hpc-gpu/jade-hpc-gpu.github.io#27]
This a request for the MD simulation software GROMACS 2018 to be installed for use on JADE as it is highly advantageous for use with JADE's GPU architecture whereas older versions are much less efficient in this aspect.

Thanks,

Alister

**Comment by LiamATOS** [comment]
Hi

Were looking into this getting installed now

Thanks

Liam

**Comment by LiamATOS** [comment]
This is now complete

Thanks

LJ

**Comment by ab24g12** [comment]
Thank you very much.

Cheers,

Alister
