### ISSUE TITLE
Software Request: Python 3.5

### ISSUE THREAD

**Issue by ogroth** [jade-hpc-gpu/jade-hpc-gpu.github.io#29]
Most OpenAI Python packages (needed in for simulation and reinforcement learning projects) only support Python 3.5. Would it be possible to also make Python 3.5 available as a module on JADE? As of now, only 2.7 and 3.6 are available.
Thanks,,
Oliver

**Comment by twinkarma** [comment]
Hi Oliver,
It is possible to request for a specific version of python by creating a virtual python environment using Anaconda. For requesting python 3.5:

```
#Loads the module first
module load python3/anaconda
#Creates a virtual environment named myenv in your home's .conda directory and requesting python 3.5 
conda create -n myenv python=3.5
#You then need to "activate" your virtual environment
source activate myenv
```
Note that your command line will how have your environment's name prefixed e.g. :

```
(myenv) my-username@my-node:~$
```

and that you will get python 3.5 when you invoke the python command:

```
(myenv) my-username@my-node:~$ python
Python 3.5.4 |Anaconda, Inc.| (default, Nov 20 2017, 18:44:38) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Then you can proceed to use python 3.5 as well as install other packages in to your home directory (using conda install or pip install)

Every session afterwards or in your batch script you need to load the module and activate the session again:

```
module load python3/anaconda
source activate myenv
```

Here's a link to the JADE's documentation on Python and Anaconda: http://docs.jade.ac.uk/en/latest/software/python.html

Best,
Twin

**Comment by LiamATOS** [comment]
Hi,

3.5.4 has been installed as a module

Thanks

Liam
ATOS

**Comment by ogroth** [comment]
Thank you very much for installing the module!
