### ISSUE TITLE
Software Request: cuDNN

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#30]
As mentioned in #25, cuDNN is essential for many GPU accelerated DL software today and would allow users to install their own DL software  easier especially for Python based packages in conjunction with Anaconda.

**Comment by andygittings** [comment]
The cuDNN 6 libraries seem to be on the login nodes in /usr/local/cuda/lib64 but not installed on the compute boxes.. (I had a user query this a day or so ago)

**Comment by LiamATOS** [comment]
We're working on this now

Thanks

Liam

**Comment by LiamATOS** [comment]
Twin,

cuDNN 7.0.5 is now available which is compatible with both Cuda 8 and 9 so we are going to install that as a module

Thanks

Liam

**Comment by twinkarma** [comment]
Would you be able to keep cuDNN 6 as well (just for  CUDA 8)? A few packages still do not support cuDNN 7 unfortunately.

**Comment by LiamATOS** [comment]
Twin,

I will install cuDNN 6 locally on the compute to match the login nodes, then install cuDNN as a Module

Thanks

Liam

**Comment by ogroth** [comment]
@LiamATOS Could you add a little clarification on which nodes and by which means CUDA and cuDNN are now available on JADE? I see both CUDA8 and CUDA9 available as modules, but cudnn6 only seems to be available under /usr/local/cuda/ on the login nodes. I tried to run my code which depends on Tensorflow 1.4, CUDA8 and cuDNN6 on the devel partition. However, despite loading the cuda8 module, only cuda9 was linked under /usr/local/cuda/ on devel and cudnn wasn't present at all. Am I doing something wrong or is CUDA8 / cuDNN6 just not available on devel?

**Comment by LiamATOS** [comment]
Apologies about this, I am aware we have a little bit of a mismatch whilst we are updating the nodes.

 I am just looking at this now and will send a clarification note once I it's complete.

Thanks

LJ

**Comment by twinkarma** [comment]
cuDNN has been added to the CUDA modules
