### ISSUE TITLE
File system quotas

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#33]
From @willprice (jade-hpc-gpu/docs#16):

Hi,

Are there space usage limits on JADE? It'd be nice to have this documented somewhere. Using lfs quota -u $USER /jmain01/data/path/to/my/data yields a quota of 0k so I assume I have 'unlimited' storage space

**Comment by twinkarma** [comment]
@willprice As you have found, there's currently no file quota but the ops team are looking to implement one soon and are under discussion as to what the limits will be.

**Comment by Parker-A** [comment]
We have made a new command available "getquota" this will show you how much space you are using & how many files you have. It will also show any disk quotas in place.
