### ISSUE TITLE
Multi nodes run

### ISSUE THREAD

**Issue by yiannisgaldadas** [jade-hpc-gpu/jade-hpc-gpu.github.io#38]
Dear Management team,

I would like to ask whether it is possible to run a job on multiple nodes because I submitted a job on JADE and I get the following warning  "PartitionNodeLimit". In the online documentation, it says that the maximum number of nodes that can be used when you submit jobs on the "big" partition is 11.

Thank you in advance for your consideration.

Kind Regards,
Yiannis

**Comment by andygittings** [comment]
Dear Yiannis,

This is correct, the system is optimised for single node multi-GPU operation - the interconnect between nodes does not have the bandwidth for inter-node GPU scaling. 

The Cambridge Tier-2 service is designed for scaling to multiple nodes/GPUs

Best regards,

Andy

**Comment by yiannisgaldadas** [comment]
Dear Andy,

Thank you very much for your reply and your suggestion on using Cambridge facilities.

Best,
Yiannis
