### ISSUE TITLE
Root partition full (devel node)

### ISSUE THREAD

**Issue by andygittings** [jade-hpc-gpu/jade-hpc-gpu.github.io#42]
The root partition /dev/sda2 is full on the devel node (dgj318)

This is causing issues running jobs on the node.

df -h
Filesystem                                      Size  Used Avail Use% Mounted on
udev                                            252G     0  252G   0% /dev
tmpfs                                            51G  202M   51G   1% /run
/dev/sda2                                       440G  417G     0 100% /
tmpfs                                           252G     0  252G   0% /dev/shm
tmpfs                                           5.0M     0  5.0M   0% /run/lock
tmpfs                                           252G     0  252G   0% /sys/fs/cgroup
/dev/sda1                                       487M  3.4M  483M   1% /boot/efi
/dev/sdb1                                       7.0T   30G  6.6T   1% /raid
172.31.126.87@o2ib:172.31.126.88@o2ib:/jmain01  904T   71T  822T   8% /jmain01

Andy

**Comment by Parker-A** [comment]
Hi
Seems fine now:
root@dgj318:~# df -h
Filesystem                                      Size  Used Avail Use% Mounted on
udev                                            252G     0  252G   0% /dev
tmpfs                                            51G  202M   51G   1% /run
/dev/sda2                                       440G   53G  364G  13% /

Adam

**Comment by andygittings** [comment]
Yes - thanks all sorted now...

Closed.
