### ISSUE TITLE
CondaHTTPError: HTTP 000 CONNECTION FAILED for url 

### ISSUE THREAD

**Issue by llyhec** [jade-hpc-gpu/jade-hpc-gpu.github.io#49]
I am getting the following connection error:

conda create -n mycode python=3.52
Fetching package metadata ...
CondaHTTPError: HTTP 000 CONNECTION FAILED for url https://repo.continuum.io/pkgs/main/linux-64/repodata.json.bz2
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/main/linux-64/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable',)))",),)_

What is the problem?
Thanks,

**Comment by llyhec** [comment]
I am getting the following connection error: 

>>>  conda create -n mycode python=3.52
Fetching package metadata ...
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/main/linux-64/repodata.json.bz2>
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/main/linux-64/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable',)))",),)

What is the problem? 

Thanks,

**Comment by willprice** [comment]
There is an issue with the proxy server providing external internet, there's a ticket open for resolving this, but no news yet

**Comment by willprice** [comment]
(see #48)
