### ISSUE TITLE
Install PyTorch?

### ISSUE THREAD

**Issue by llyhec** [jade-hpc-gpu/jade-hpc-gpu.github.io#50]
# Software Request

Would it be possible to install pytorch? Is it already installed, I can't seem to find it? Are there any instructions on how to use it?

**Comment by LiamATOS** [comment]
This is installed as container already

exs66-ljj01@dgj419:~$ containers
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
nvcr.io/nvidia/pytorch      17.12               5ac6ff8f9a81        5 months ago        4.52GB

**Comment by willprice** [comment]
Alternatively you can use anaconda to use it, which is available as a module, see `module avail`

**Comment by llyhec** [comment]
thank you.
