### ISSUE TITLE
Software Request TensorFlow 1.7 (Nvidia container 18.04-py2)

### ISSUE THREAD

**Issue by andygittings** [jade-hpc-gpu/jade-hpc-gpu.github.io#53]
Please could we have the Nvidia 18.04-py2 TensorFlow container installed, as it is needed for benchmarking against our local DGX1V system

Thanks,

Andy

**Comment by LiamATOS** [comment]
Hi Andy, 

I am looking at this now but we seem to have an issue with the NVidia repo's which I think may have been caused by the DGX Update, I have raised a support ticket with them.

Thanks

Liam

**Comment by andygittings** [comment]
Thanks Liam.

Andy

**Comment by LiamATOS** [comment]
This is currently being installed now, will update you once its available on all of the nodes.

Sorry for the delay.

Liam

**Comment by LiamATOS** [comment]
This is now done

Thanks

Liam
