### ISSUE TITLE
Ensure `devel` partition limit.

### ISSUE THREAD

**Issue by we-taper** [jade-hpc-gpu/jade-hpc-gpu.github.io#65]
According to the [documentation](http://docs.jade.ac.uk/en/latest/jade/scheduler/index.html?highlight=devel), the `devel` partition has a `Job Walltime limit` of an hour, and a `Running Job limit` of 1. But according to `squeue` result, these rules have been breached **very often by so many people**. Could someone ensure that these requirements are met, or is the documentation outdated?

**Comment by Parker-A** [comment]
Hi
Sorry about this, it was adjusted a while back for a user to try out some MPI jobs. Looks like other people are abusing it. We will put it back to how it should be.
