### ISSUE TITLE
Change in job limit on the small partition?

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#78]
I've got a query from a JADE user @obabiola:

I am currently getting the following message when I try  to submit jobs on JADE:

```
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)
```

The documentation says there is a limit of 16 jobs per user on the "small" job partition, and I currently have 8 jobs running.

Do you know if the job limit has changed ?

@LiamATOS Any ideas?

**Comment by LiamATOS** [comment]
Hi Twin,

Yes it was agreed to lower this a couple of weeks ago.

@andygittings who is responsible for updating the relevant documentation?

Thanks

Liam

**Comment by twinkarma** [comment]
Great, thanks for the quick response.
