### ISSUE TITLE
Problem running singbatch "--nv not found"

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#82]
@yiminking reported problems running the singularity script `singbatch`. She got the following error:

The job script
```
#!/bin/bash

#set the number of nodes
#SBATCH --nodes=1

# set max wallclock time
#SBATCH --time=1:00:00

# set number of GPUs
#SBATCH --gres=gpu:1

#SBATCH --partition=devel

chmod +x script.sh
#Launching the commands within script.sh
module load singularity
singbatch /jmain01/home/JAD009/txk08/yxw50-txk08/1.9.0-GPU-Ubuntu16.04-Anaconda3.4.2.0-CUDA9-cudNN7.simg ./script.sh
```

The error
```
Singularity-2.4 loaded
/.singularity.d/actions/exec: 9: exec: --nv: not found
``` 

I've also tried it myself using my own singularity image and also get the same `--nv not found` error. 

Having had a look at the `singbatch` code I noticed that the --nv flag is placed after the image name (so is the -B flag) instead of before it which is what's causing the errors. The correct order should be:

```
singularity exec --nv -B outsidepath:insidepath imagename.simg myscript.sh
```

Also I've noticed that the singularity version is 2.4, I think it might be a good idea to also update it to a more current version (I think there's a version 3.0 now). 

@LiamATOS

**Comment by willprice** [comment]
:+1: on getting a new version of Singularity, the team have pushed a bunch of useful changes that'd be good to use on JADE.
Cheers

**Comment by agniszczotka** [comment]
@twinkarma I am run to the same problem plus permission denied error when running singbath
`mkdir: cannot create directory ‘/raid’: Permission denied`
`/.singularity.d/actions/exec: 9: exec: --nv: not found`

**Comment by twinkarma** [comment]
@willprice @LiamATOS The singbatch script also has the exact same problem where --nv flag should be called after the exec command rather than after the image name. Can we get this fixed?

Here is the line from the `singbatch` script:

```
# Now run the container, with the users home directy & local scratch - give it the script at the end!
singularity exec $1 --nv -B /raid/local_scratch/$SLURM_JOB_USER-$SLURM_JOB_ID:/local_scratch,/raid/local_scratch/$SLURM_JOB_USER-$SLURM_JOB_ID/.tmp:/tmp $2

```

**Comment by twinkarma** [comment]
Closed due to inactivity
