### ISSUE TITLE
singularity container - sudo password required

### ISSUE THREAD

**Issue by agniszczotka** [jade-hpc-gpu/jade-hpc-gpu.github.io#92]
I have tried to build a singularity container based on build.sh and tensorflow script like in https://github.com/rses-singularity/all-images.
The script requires a password for my account, but my SAFE password does not work.
```
Building image tensorflow.simg from tensorflow/Singularity
[sudo] password for aas75-mxm01: 
Sorry, try again.

```
How can I generate/change the password for my account?

**Comment by twinkarma** [comment]
Unfortunately, to build images you need root access. This means you'll have to build images on your local machine where you have that permission and then upload it to JADE or use something like [singularity hub](https://singularity-hub.org).

**Comment by agniszczotka** [comment]
thank you for clarifying. 
Could you please tell me how I can ensure that I am using correct GPUs with my container to avoid abusing computing nodes?

**Comment by twinkarma** [comment]
The environment variables that are used to lock the GPUs should also be present inside the Singularity image so there's need for extra consideration in that regard.

**Comment by agniszczotka** [comment]
Could you please specify how to get the environment variables which shows which GPUs are given by scheduler to set CUDA_VISIBLE_DEVICES in the container?
I can't see clear description at https://jade-hpc.readthedocs.io/en/latest/jade/containers.html

**Comment by agniszczotka** [comment]
thank you for clarifying. It would be helpful to see that information at JADE doc website. It was not straightforward to understand it for me.

**Comment by twinkarma** [comment]
It's a bit of difficult one. While it might be more informative, the CUDA_VISIBLE_DEVICES is managed automatically and should work transparently for users without the knowledge of it. In fact, having people set it themselves will lead to GPU conflicts. That's why we decided not to promote it back then.

**Comment by twinkarma** [comment]
Ah in fact we do mention on the docs page to not touch the visible_devices flag.

**Comment by agniszczotka** [comment]
it sounds like an ideal solution to not touch  CUDA_VISIBLE_DEVICES. I think that this issue can be resolved. Thank you for providing me with a transparent explanation.
